const state={bible:null,bookIndex:0,chapter:0,lang:'en',bookmarks:JSON.parse(localStorage.getItem('akosibiko-bookmarks')||'[]')};
const booksMeta=[
['Genesis','OT'],['Exodus','OT'],['Leviticus','OT'],['Numbers','OT'],['Deuteronomy','OT'],['Joshua','OT'],['Judges','OT'],['Ruth','OT'],['1 Samuel','OT'],['2 Samuel','OT'],['1 Kings','OT'],['2 Kings','OT'],['1 Chronicles','OT'],['2 Chronicles','OT'],['Ezra','OT'],['Nehemiah','OT'],['Esther','OT'],['Job','OT'],['Psalms','OT'],['Proverbs','OT'],['Ecclesiastes','OT'],['Song of Solomon','OT'],['Isaiah','OT'],['Jeremiah','OT'],['Lamentations','OT'],['Ezekiel','OT'],['Daniel','OT'],['Hosea','OT'],['Joel','OT'],['Amos','OT'],['Obadiah','OT'],['Jonah','OT'],['Micah','OT'],['Nahum','OT'],['Habakkuk','OT'],['Zephaniah','OT'],['Haggai','OT'],['Zechariah','OT'],['Malachi','OT'],['Matthew','NT'],['Mark','NT'],['Luke','NT'],['John','NT'],['Acts','NT'],['Romans','NT'],['1 Corinthians','NT'],['2 Corinthians','NT'],['Galatians','NT'],['Ephesians','NT'],['Philippians','NT'],['Colossians','NT'],['1 Thessalonians','NT'],['2 Thessalonians','NT'],['1 Timothy','NT'],['2 Timothy','NT'],['Titus','NT'],['Philemon','NT'],['Hebrews','NT'],['James','NT'],['1 Peter','NT'],['2 Peter','NT'],['1 John','NT'],['2 John','NT'],['3 John','NT'],['Jude','NT'],['Revelation','NT']];
const notes={
'en':{
 intro:['Bible Baptist Study Framework','This is an original study aid, not a reproduction of any commercial study Bible. It reads Scripture from a Bible Baptist, Free Grace, dispensational perspective and encourages the reader to compare every doctrine with the KJV text.'],
 salvation:['Salvation — Grace and Faith','Salvation is presented as God’s free gift, received by faith in Jesus Christ rather than earned by works. Christ’s atoning provision is understood as sufficient for all people, while only believers receive its saving benefit.','John 3:16','Ephesians 2:8-9','Romans 10:9-10'],
 security:['Eternal Security','This framework teaches that a truly saved believer is eternally secure. The believer is sealed by the Holy Spirit and salvation rests on God’s promise, not on the believer’s ability to maintain a sinless life. Growth, obedience, discipline, rewards, and fellowship should not be confused with the gift of eternal life.','Ephesians 1:13-14','John 10:27-29','Romans 8:38-39'],
 disp:['Dispensational Reading','Scripture is read with attention to the distinct administrations in God’s program. A classic outline is Innocence, Conscience, Human Government, Promise, Law, Grace, and Kingdom. Dispensational distinctions should clarify the text rather than divide the Bible into unrelated messages.','2 Timothy 2:15','Ephesians 3:1-6','Revelation 20:1-6'],
 eschatology:['Pre-Tribulation / Pre-Millennial Hope','This study framework understands the church’s catching away as a future event preceding the Tribulation, followed by Christ’s literal return and a literal thousand-year reign. These are interpretive convictions; the reader should study the passages directly.','1 Thessalonians 4:13-18','1 Corinthians 15:51-52','Revelation 19:11-20:6'],
 baptist:['Bible Baptist Distinctives','Emphasis is placed on the authority of Scripture, salvation by grace through faith, believer’s baptism by immersion, the autonomy of the local church, the priesthood of believers, and separation from religious systems that compromise biblical convictions.','Matthew 28:19-20','Acts 2:41','1 Corinthians 1:2'],
 bibliology:['KJV / Received Text Note','The KJV is treated here as the reading text of the project, with appreciation for the traditional Textus Receptus / Received Text heritage. The site does not reproduce proprietary notes from commercial KJV study editions.','Psalm 12:6-7','2 Timothy 3:16-17','1 Peter 1:25'],
 glossary:['Archaic KJV Glossary','Quick meanings: conversation = conduct/way of life; prevent = precede; meat = food; charity = self-giving love; suffer = allow/permit or endure depending on context; peculiar = specially belonging; quick = living; corn = grain. Always check the verse context.'],
 tools:['Study Tools','Use the bookmark star on a chapter, search the complete corpus, switch study-note language, and select any cross-reference to open the referenced passage.']
},
'ceb':{
 intro:['Bible Baptist Study Framework','Kini usa ka orihinal nga study aid, dili kopya sa komersyal nga Study Bible. Ang mga nota nagtan-aw sa Kasulatan gikan sa Bible Baptist, Free Grace, ug dispensational nga panan-aw. Ikumpara kanunay ang matag pagtulon-an sa teksto sa KJV.'],
 salvation:['Kaluwasan — Grasya ug Pagtoo','Ang kaluwasan mao ang libre nga gasa sa Dios nga madawat pinaagi sa pagtoo kang Jesus Cristo, dili pinaagi sa mga buhat. Ang buhat ni Cristo igo alang sa tanan, apan ang makadawat pinaagi sa pagtoo mao ang maluwas.','John 3:16','Ephesians 2:8-9','Romans 10:9-10'],
 security:['Walay Katapusan nga Seguridad','Kini nga framework nagtudlo nga ang tinuod nga magtutuo walay katapusan nga seguridad sa kaluwasan. Ang magtutuo gisilyohan sa Espiritu Santo, ug ang kaluwasan nagsalig sa saad sa Dios, dili sa hingpit nga performance sa tawo.','Ephesians 1:13-14','John 10:27-29','Romans 8:38-39'],
 disp:['Dispensational nga Pagbasa','Ang Kasulatan basahon uban sa pagtagad sa lain-laing administrasyon sa plano sa Dios: Innocence, Conscience, Human Government, Promise, Law, Grace, ug Kingdom. Ang mga kalainan kinahanglan makatabang sa pagsabot sa teksto.','2 Timothy 2:15','Ephesians 3:1-6','Revelation 20:1-6'],
 eschatology:['Pre-Tribulation / Pre-Millennial','Kini nga framework nagtuo sa umaabot nga Rapture sa iglesia una sa Tribulation, dayon sa literal nga pagbalik ni Cristo ug sa literal nga usa ka libo ka tuig nga paghari. Pagtuon gihapon sa mga teksto mismo.','1 Thessalonians 4:13-18','1 Corinthians 15:51-52','Revelation 19:11-20:6'],
 baptist:['Bible Baptist Distinctives','Gihatagan og gibug-aton ang awtoridad sa Kasulatan, kaluwasan pinaagi sa grasya ug pagtoo, baptism pinaagi sa immersion sa magtutuo, kagawasan sa local church, priesthood sa mga magtutuo, ug separation gikan sa mga sistema nga mosupak sa biblical convictions.','Matthew 28:19-20','Acts 2:41','1 Corinthians 1:2'],
 bibliology:['KJV / Received Text','Ang KJV mao ang reading text niini nga proyekto, uban sa pagpasidungog sa traditional Textus Receptus / Received Text heritage. Dili kopyahon dinhi ang proprietary notes sa commercial study editions.','Psalm 12:6-7','2 Timothy 3:16-17','1 Peter 1:25'],
 glossary:['KJV Archaic Glossary','conversation = pamatasan o paagi sa kinabuhi; prevent = una/mauna; meat = pagkaon; charity = gugma nga mapinanggaon; suffer = tugotan o antuson depende sa context; peculiar = espesyal nga iya; quick = buhi; corn = lugas.'],
 tools:['Mga Himan sa Pagtuon','Gamita ang star aron ma-bookmark ang chapter, pangitaa ang tibuok KJV, ilisi ang pinulongan sa notes, ug i-click ang cross-reference aron maablihan ang passage.']
},
'tl':{
 intro:['Bible Baptist Study Framework','Ito ay orihinal na study aid at hindi kopya ng anumang komersyal na Study Bible. Ang mga tala ay nakabatay sa Bible Baptist, Free Grace, at dispensational na pananaw. Ihambing palagi ang bawat aral sa teksto ng KJV.'],
 salvation:['Kaligtasan — Biyaya at Pananampalataya','Ang kaligtasan ay libreng kaloob ng Diyos na tinatanggap sa pananampalataya kay Jesucristo, hindi sa mga gawa. Ang handog ni Cristo ay sapat para sa lahat, ngunit ang nananampalataya ang tumatanggap ng kaligtasan.','John 3:16','Ephesians 2:8-9','Romans 10:9-10'],
 security:['Walang Hanggang Seguridad','Itinuturo ng framework na ito na ang tunay na mananampalataya ay ligtas magpakailanman. Siya ay tinatakan ng Espiritu Santo, at ang kaligtasan ay nakasalig sa pangako ng Diyos, hindi sa kakayahan ng tao na mamuhay nang walang kasalanan.','Ephesians 1:13-14','John 10:27-29','Romans 8:38-39'],
 disp:['Dispensational na Pagbasa','Binabasa ang Kasulatan ayon sa magkakaibang administrasyon sa plano ng Diyos: Innocence, Conscience, Human Government, Promise, Law, Grace, at Kingdom. Dapat itong makatulong sa malinaw na pagbasa ng teksto.','2 Timothy 2:15','Ephesians 3:1-6','Revelation 20:1-6'],
 eschatology:['Pre-Tribulation / Pre-Millennial','Ang framework na ito ay naniniwala sa hinaharap na Rapture ng iglesia bago ang Tribulation, pagkatapos ay literal na pagbabalik ni Cristo at literal na isang libong taong paghahari. Pag-aralan pa rin ang mismong mga talata.','1 Thessalonians 4:13-18','1 Corinthians 15:51-52','Revelation 19:11-20:6'],
 baptist:['Bible Baptist Distinctives','Binibigyang-diin ang awtoridad ng Kasulatan, kaligtasan sa biyaya sa pamamagitan ng pananampalataya, bautismo ng mananampalataya sa pamamagitan ng immersion, kasarinlan ng lokal na iglesia, priesthood ng mga mananampalataya, at paghihiwalay sa mga sistemang salungat sa biblical convictions.','Matthew 28:19-20','Acts 2:41','1 Corinthians 1:2'],
 bibliology:['KJV / Received Text','Ang KJV ang pangunahing reading text ng proyektong ito, na may pagpapahalaga sa tradisyong Textus Receptus / Received Text. Hindi kinokopya rito ang proprietary notes ng mga komersyal na study edition.','Psalm 12:6-7','2 Timothy 3:16-17','1 Peter 1:25'],
 glossary:['KJV Archaic Glossary','conversation = asal o paraan ng pamumuhay; prevent = mauna; meat = pagkain; charity = pag-ibig na nagbibigay; suffer = payagan o tiisin ayon sa konteksto; peculiar = natatanging pag-aari; quick = buhay; corn = butil.'],
 tools:['Mga Study Tool','Gamitin ang star para i-bookmark ang chapter, hanapin ang buong KJV, palitan ang wika ng notes, at piliin ang cross-reference para buksan ang kaugnay na talata.']
}};
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function bookName(b){return b.book||b.name||b.title}
function chapters(b){return b.chapters||[]}
function verses(c){return c.verses||c}
function verseText(v){return typeof v==='string'?v:(v.text||v.verse||'')}
function parseRef(ref){const m=ref.match(/^(.+?)\s+(\d+)(?::(\d+))?$/);return m?{book:m[1],chapter:+m[2],verse:m[3]?+m[3]:1}:null}
function renderBooks(){const el=document.getElementById('books');el.innerHTML='';let last='';state.bible.forEach((b,i)=>{const n=bookName(b),t=booksMeta[i]?.[1]||'';if(t!==last){const d=document.createElement('div');d.className='testament';d.textContent=t==='OT'?'Old Testament':'New Testament';el.appendChild(d);last=t}const btn=document.createElement('button');btn.textContent=n;btn.className=i===state.bookIndex?'active':'';btn.onclick=()=>{state.bookIndex=i;state.chapter=0;renderBooks();renderChapter()};el.appendChild(btn)})}
function renderChapter(){const b=state.bible[state.bookIndex], cs=chapters(b), c=cs[state.chapter]||{};const name=bookName(b);document.getElementById('title').textContent=name;document.getElementById('chapterTitle').textContent=`Chapter ${state.chapter+1} • ${verses(c).length} verses`;const sel=document.getElementById('chapter');sel.innerHTML=cs.map((_,i)=>`<option value="${i}" ${i===state.chapter?'selected':''}>Chapter ${i+1}</option>`).join('');document.getElementById('verses').innerHTML=verses(c).map((v,i)=>{const ref=`${name} ${state.chapter+1}:${i+1}`;const marked=state.bookmarks.includes(ref);return `<p class="verse ${marked?'marked':''}" id="v-${i+1}"><span class="vnum">${i+1}</span>${esc(verseText(v))}<button title="${marked?'Remove':'Bookmark'}" onclick="toggleVerseBookmark('${ref}')">${marked?'★':'☆'}</button></p>`}).join('');document.getElementById('bookmarkBtn').textContent=state.bookmarks.includes(`${name} ${state.chapter+1}`)?'★ Bookmarked':'☆ Bookmark';window.scrollTo({top:0,behavior:'smooth'})}
window.toggleVerseBookmark=function(ref){if(state.bookmarks.includes(ref))state.bookmarks=state.bookmarks.filter(x=>x!==ref);else state.bookmarks.push(ref);localStorage.setItem('akosibiko-bookmarks',JSON.stringify(state.bookmarks));renderChapter();toast(state.bookmarks.includes(ref)?'Saved to bookmarks':'Removed from bookmarks')}
function renderStudy(){const n=notes[state.lang];const order=['intro','salvation','security','disp','eschatology','baptist','bibliology','glossary','tools'];document.getElementById('studyContent').innerHTML=order.map(k=>{const x=n[k];if(k==='glossary'||k==='tools'||k==='intro')return `<div class="study-section"><h4>${esc(x[0])}</h4><p>${esc(x[1])}</p></div>`;return `<div class="study-section"><span class="badge">${esc(x[0])}</span><p>${esc(x[1])}</p><div>${x.slice(2).map(r=>`<span class="xref" onclick="openRef('${esc(r)}')">${esc(r)}</span>`).join('')}</div></div>`}).join('')}
window.openRef=function(ref){const p=parseRef(ref);if(!p)return;const i=state.bible.findIndex(b=>bookName(b).toLowerCase()===p.book.toLowerCase());if(i<0){toast('Reference not found in this KJV corpus');return}state.bookIndex=i;state.chapter=Math.max(0,p.chapter-1);renderBooks();renderChapter();setTimeout(()=>{const v=document.getElementById('v-'+p.verse);v?.scrollIntoView({behavior:'smooth',block:'center'});v?.classList.add('marked')},250)}
function search(q){q=q.trim().toLowerCase();const box=document.getElementById('results');if(!q){box.style.display='none';return}let arr=[];for(let bi=0;bi<state.bible.length&&arr.length<80;bi++){const b=state.bible[bi],cs=chapters(b);for(let ci=0;ci<cs.length&&arr.length<80;ci++){const vs=verses(cs[ci]);for(let vi=0;vi<vs.length&&arr.length<80;vi++){const tx=verseText(vs[vi]);if(tx.toLowerCase().includes(q))arr.push({bi,ci,vi,tx})}}}box.innerHTML=arr.length?arr.map(x=>`<div class="result" data-bi="${x.bi}" data-ci="${x.ci}" data-vi="${x.vi}"><strong>${esc(bookName(state.bible[x.bi]))} ${x.ci+1}:${x.vi+1}</strong><br><small>${esc(x.tx.slice(0,180))}${x.tx.length>180?'…':''}</small></div>`).join(''):`<div class="result">No matching verses.</div>`;box.style.display='block';box.querySelectorAll('.result[data-bi]').forEach(e=>e.onclick=()=>{state.bookIndex=+e.dataset.bi;state.chapter=+e.dataset.ci;renderBooks();renderChapter();box.style.display='none';setTimeout(()=>document.getElementById('v-'+(+e.dataset.vi+1))?.scrollIntoView({behavior:'smooth',block:'center'}),150)})}
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.style.display='block';setTimeout(()=>e.style.display='none',1800)}
async function load(){try{const res=await fetch('data/kjv.json');if(!res.ok)throw Error();state.bible=await res.json();document.getElementById('status').textContent='Offline-ready • KJV loaded';renderBooks();renderChapter();renderStudy();startClock()}catch(e){document.getElementById('status').textContent='KJV data not bundled yet';document.getElementById('verses').innerHTML='<div class="empty"><h3>Build the complete KJV corpus</h3><p>Run <code>node scripts/prepare-data.mjs</code> locally, or push this repository to GitHub and let the included Pages workflow download the public-domain KJV data during deployment.</p></div>';renderStudy()}}
document.getElementById('chapter').onchange=e=>{state.chapter=+e.target.value;renderChapter()};document.getElementById('prev').onclick=()=>{if(state.chapter>0)state.chapter--;else if(state.bookIndex>0){state.bookIndex--;state.chapter=chapters(state.bible[state.bookIndex]).length-1;renderBooks()}renderChapter()};document.getElementById('next').onclick=()=>{if(state.chapter<chapters(state.bible[state.bookIndex]).length-1)state.chapter++;else if(state.bookIndex<state.bible.length-1){state.bookIndex++;state.chapter=0;renderBooks()}renderChapter()};document.getElementById('bookmarkBtn').onclick=()=>{const ref=`${bookName(state.bible[state.bookIndex])} ${state.chapter+1}`;toggleVerseBookmark(ref)};document.getElementById('search').oninput=e=>search(e.target.value);document.getElementById('searchBtn').onclick=()=>search(document.getElementById('search').value);document.querySelectorAll('.lang-tabs button').forEach(b=>b.onclick=()=>{state.lang=b.dataset.lang;document.querySelectorAll('.lang-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderStudy()});document.getElementById('close').onclick=()=>document.getElementById('modal').classList.remove('open');
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;document.getElementById('install').hidden=false});document.getElementById('install').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null}};
function startClock(){const el=document.getElementById('status');setInterval(()=>{const d=new Date();el.title='Local time: '+d.toLocaleString();},1000)}
load();
